# Generated by Django 5.1 on 2025-01-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Salse",
            new_name="Sales",
        ),
        migrations.RenameField(
            model_name="sales",
            old_name="sales_data",
            new_name="sales_date",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="purchase_data",
        ),
    ]
