# Generated by Django 5.1 on 2025-01-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_rename_salse_sales_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="purchase_date",
            field=models.DateField(null=True, verbose_name="仕入日時"),
        ),
        migrations.AlterField(
            model_name="sales",
            name="sales_date",
            field=models.DateField(verbose_name="売上"),
        ),
    ]
