# Generated by Django 5.1 on 2025-01-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_purchase_purchase_date_alter_sales_sales_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="purchase_date",
            field=models.DateTimeField(null=True, verbose_name="仕入日時"),
        ),
        migrations.AlterField(
            model_name="sales",
            name="sales_date",
            field=models.DateTimeField(verbose_name="売上"),
        ),
    ]
